Repository charmbracelet/lipgloss, pull requests merged in 2022-02, with the labels that each got.

#61 Lazily detect background color setting
  color.go
Labels: enhancement

#62 Bump termenv dependency
  example/go.sum
  go.mod
  go.sum
Labels: bug

#63 Fix typo in AdaptiveColor's godoc comment
  color.go
Labels: documentation

#64 Use termenv's EnvColorProfile, which respects NO_COLOR and CLICOLOR_FORCE env vars
  color.go
Labels: enhancement

#66 Add Value method
  style.go
Labels: enhancement
