Repository charmbracelet/lipgloss, pull requests merged in 2024-10, with the labels that each got.

#377 fix: shared indices for first row of data and headers (StyleFunc bug)
  table/table.go
  table/table_test.go
  table/testdata/TestStyleFunc.golden
Labels: bug

#96 docs(example): rainbow string
  examples/go.mod
  examples/go.sum
  examples/layout/main.go
Labels: documentation

#395 fix(examples): fix out of range error
  examples/table/languages/main.go
  examples/table/mindy/main.go
  examples/table/pokemon/main.go
Labels: bug

#373 fix(table): do not shrink table with offset
  table/table.go
  table/table_test.go
Labels: bug

#416 (v2) fix: query both stdin and stdout for background color on non-Windows …
  query.go
Labels: v2
